# Use root as user credentials
# Before running compose-up command , create network. for example "docker network create mysql8"
version: "3.1"

services:
  mysql8:
    container_name: mysql8
    image: mysql:8.0.23
    platform: linux/amd64
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --transaction-isolation=READ-COMMITTED
    environment:
      MYSQL_ROOT_PASSWORD: kakobank2022
    ports:
      - 3306:3306
    networks:
      - mysql8

networks:
  mysql8:
    external:
      name: mysql8

volumes:
  db_data:
