# Use root as user credentials
# Before running compose-up command , create network. for example "docker network create mysql8"
version: "3.1"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.23
    platform: linux/x86_64
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --transaction-isolation=READ-COMMITTED
    environment:
      MYSQL_ROOT_PASSWORD: kakaobank2022
    ports:
      - 3306:3306

volumes:
  db_data:
