### 상위 검색 키워드 top 10
GET http://localhost:4000/v1/kakaobank/search/keywords
Accept: application/json

### 장소 키워드 검색
GET http://localhost:4000/v1/kakaobank/search/locations?keyword=서울
Accept: application/json